# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '2c407aefb7c09c96e3a973bd2cb5c37b'
  config.secret_key = '370418077ea64e650f9ccb75a4c9178b'
  config.default_from = 'no-reply-to-kasu@yopmail.com'
  config.api_version = 'v3.1'
end
